export enum TokenType {
  LEFT_PAREN, RIGHT_PAREN,
  LEFT_BRACE, RIGHT_BRACE,
  MINUS,//~
  PLUS, COMMA, SEMICOLON, SLASH, STAR, 
  EQUAL, NOT_EQUAL,
  GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
  ARROW, CARET, COLON, CONS, PIPE,
  NEW_LINE,//\n
  RANGE,// ..
  HASH,//#
  QUES,//?
  AMPERSAND,//&
  EXCL,//!
  NEGATE, //~
  ADD_SHORT,//+=
  //GENERICS
  GEN_OPEN, GEN_CLOSE,
  //CASE comment
  CASE_COMM,//--
  //Literals
  IDENTIFIER, STRING, NUMBER,
  COMMENT,
  //Keywords
  ANDALSO, ORELSE, TRUE, FALSE, 
  CASE, OF, FUN, VAL,

  EOF
}